# Generated by Django 4.2.6 on 2023-10-11 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
