# Generated by Django 4.2.6 on 2023-10-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_data_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data_reserva',
            new_name='data',
        ),
    ]
